
services:

  expensy_mongodb:
    image: mongo:6
    container_name: expensy_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - expensy_network

  expensy_redis:
    image: redis:7
    container_name: expensy_redis
    restart: always
    command: ["redis-server", "--requirepass", "someredispassword"]
    ports:
      - "6379:6379"
    networks:
      - expensy_network

  expensy_backend:
    container_name: expensy_backend
    build:
      context: ./expensy_backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    depends_on:
      - expensy_mongodb
      - expensy_redis
    ports:
      - "8706:8706"
    networks:
      - expensy_network

  expensy_frontend:
    container_name: expensy_frontend
    build:
      context: ./expensy_frontend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    depends_on:
      - expensy_backend
    ports:
      - "3000:3000"
    networks:
      - expensy_network

networks:
  expensy_network:
    driver: bridge

volumes:
  mongo_data:

